---
abstract: 'Retrieves information of RT tickets'
author:
  - "Damien \"dams\" Krotkine <dams@cpan.org>"
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-BasicBot-Pluggable-Module-RT
provides:
  Bot::BasicBot::Pluggable::Module::RT:
    file: lib/Bot/BasicBot/Pluggable/Module/RT.pm
    version: 0.04
requires:
  Bot::BasicBot::Pluggable: 0.5
  RT::Client::REST: 0
  RT::Client::REST::Ticket: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
