# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bot-BasicBot-Pluggable-Module-RT
version:      0.03
version_from: lib/Bot/BasicBot/Pluggable/Module/RT.pm
installdirs:  site
requires:
    RT::Client::REST:              0
    RT::Client::REST::Ticket:      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
